spring:
  application:
    name: NetflixBackend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/netflix
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: trung8d2005@gmail.com
    password: hgai jwqa dagf avgw
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

file:
  uploads:
    video-dir: uploads/videos
    image-dir: uploads/images

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
jwt:
  secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NzEwNzY2NjcsImV4cCI6MTc3MzY2ODY2NywianRpIjoiYzQyN2Y2ZDktNWJjNS00NDFkLTg1YjYtNGNjYWU5ZDIwMjk0IiwiaXNzIjoiYXBpLmV4YW1wbGUuY29tIiwic3ViIjoidXNlcl84MjYzIiwiYXVkIjoiaHR0cHM6Ly9leGFtcGxlLmNvbSJ9.J9O7x4IfZnfdtDjFA8UftB9xHkv70PEJwR-oRA9IDPUyRdG8VTYJauzXvtKafbTOwEy8fKeeBzU3fSdVL_JJoQ
app:
  frontend:
    url: http://localhost:4200
